trigger:
- main
pool: 
  vmImage: ubuntu-latest


variables:
  buildConfiguration: 'Release'

steps: 
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'
- task: UseMSStoreCLI@0
  inputs:
    version: 'latest'