trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dotnet restore
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration) --no-build
